### ISSUE TITLE
Lack of currency values

### ISSUE THREAD

**Issue by yaskael** [PCGamingEra/Enhanced_Steam#1]
Currency values aren't currently up to date resulting in broken currency conversions.

**Comment by ColdSunERA** [comment]
Provide a full list of the country codes that the EnhancedSteam API provides, and I'll update ours.

**Comment by yaskael** [comment]
[{"base":"USD","EUR":"0.873829","GBP":"0.783477","USD":"1","RUB":"66.8512","BRL":"3.73572"},{"base":"GBP","EUR":"1.11532","GBP":"1","USD":"1.27636","RUB":"85.3263","BRL":"4.76813"},{"base":"EUR","EUR":"1","GBP":"0.896602","USD":"1.14439","RUB":"76.5038","BRL":"4.27511"},{"base":"RUB","EUR":"0.0130713","GBP":"0.0117197","USD":"0.0149586","RUB":"1","BRL":"0.0558811"},{"base":"BRL","EUR":"0.233912","GBP":"0.209726","USD":"0.267686","RUB":"17.8951","BRL":"1"},{"base":"JPY","EUR":"0.00803264","GBP":"0.00720208","USD":"0.00919246","RUB":"0.614527","BRL":"0.0343404"},{"base":"NOK","EUR":"0.102225","GBP":"0.0916552","USD":"0.116985","RUB":"7.8206","BRL":"0.437023"},{"base":"IDR","EUR":"0.0000618246","GBP":"0.0000554321","USD":"0.0000707514","RUB":"0.00472981","BRL":"0.000264307"},{"base":"MYR","EUR":"0.212559","GBP":"0.190581","USD":"0.24325","RUB":"16.2616","BRL":"0.908713"},{"base":"PHP","EUR":"0.0166426","GBP":"0.0149218","USD":"0.0190456","RUB":"1.27322","BRL":"0.0711491"},{"base":"SGD","EUR":"0.643383","GBP":"0.576858","USD":"0.73628","RUB":"49.2212","BRL":"2.75053"},{"base":"THB","EUR":"0.0272667","GBP":"0.0244474","USD":"0.0312037","RUB":"2.086","BRL":"0.116568"},{"base":"VND","EUR":"0.0000376771","GBP":"0.0000337813","USD":"0.0000431172","RUB":"0.00288244","BRL":"0.000161074"},{"base":"KRW","EUR":"0.000777286","GBP":"0.000696916","USD":"0.000889517","RUB":"0.0594653","BRL":"0.00332299"},{"base":"TRY","EUR":"0.162061","GBP":"0.145304","USD":"0.185461","RUB":"12.3983","BRL":"0.692829"},{"base":"UAH","EUR":"0.0315013","GBP":"0.0282441","USD":"0.0360497","RUB":"2.40997","BRL":"0.134672"},{"base":"MXN","EUR":"0.0450448","GBP":"0.0403873","USD":"0.0515487","RUB":"3.44609","BRL":"0.192571"},{"base":"CAD","EUR":"0.657921","GBP":"0.589893","USD":"0.752917","RUB":"50.3334","BRL":"2.81269"},{"base":"AUD","EUR":"0.622501","GBP":"0.558135","USD":"0.712383","RUB":"47.6236","BRL":"2.66126"},{"base":"NZD","EUR":"0.588945","GBP":"0.52805","USD":"0.673983","RUB":"45.0565","BRL":"2.51781"},{"base":"INR","EUR":"0.012462","GBP":"0.0111734","USD":"0.0142613","RUB":"0.953387","BRL":"0.0532763"},{"base":"HKD","EUR":"0.111481","GBP":"0.0999542","USD":"0.127578","RUB":"8.52872","BRL":"0.476594"},{"base":"TWD","EUR":"0.028309","GBP":"0.0253819","USD":"0.0323965","RUB":"2.16575","BRL":"0.121024"},{"base":"CNY","EUR":"0.127435","GBP":"0.114258","USD":"0.145835","RUB":"9.74922","BRL":"0.544797"},{"base":"SAR","EUR":"0.232984","GBP":"0.208894","USD":"0.266624","RUB":"17.8241","BRL":"0.996032"},{"base":"ZAR","EUR":"0.0626515","GBP":"0.0561735","USD":"0.0716977","RUB":"4.79308","BRL":"0.267842"},{"base":"AED","EUR":"0.237894","GBP":"0.213297","USD":"0.272244","RUB":"18.1998","BRL":"1.01702"},{"base":"CHF","EUR":"0.89065","GBP":"0.798559","USD":"1.01925","RUB":"68.1381","BRL":"3.80763"},{"base":"CLP","EUR":"0.00128256","GBP":"0.00114995","USD":"0.00146775","RUB":"0.0981208","BRL":"0.0054831"},{"base":"PEN","EUR":"0.260669","GBP":"0.233717","USD":"0.298307","RUB":"19.9422","BRL":"1.11439"},{"base":"COP","EUR":"0.000273728","GBP":"0.000245425","USD":"0.000313251","RUB":"0.0209412","BRL":"0.00117022"},{"base":"UYU","EUR":"0.0268769","GBP":"0.0240979","USD":"0.0307577","RUB":"2.05619","BRL":"0.114902"},{"base":"ILS","EUR":"0.235683","GBP":"0.211314","USD":"0.269713","RUB":"18.0306","BRL":"1.00757"},{"base":"PLN","EUR":"0.232718","GBP":"0.208656","USD":"0.26632","RUB":"17.8038","BRL":"0.994897"},{"base":"ARS","EUR":"0.0234308","GBP":"0.0210081","USD":"0.026814","RUB":"1.79255","BRL":"0.100169"},{"base":"CRC","EUR":"0.00144558","GBP":"0.00129611","USD":"0.0016543","RUB":"0.110592","BRL":"0.00618001"},{"base":"KZT","EUR":"0.00232961","GBP":"0.00208873","USD":"0.00266598","RUB":"0.178224","BRL":"0.00995935"},{"base":"KWD","EUR":"2.88292","GBP":"2.58483","USD":"3.29918","RUB":"220.554","BRL":"12.3248"},{"base":"QAR","EUR":"0.239992","GBP":"0.215177","USD":"0.274644","RUB":"18.3603","BRL":"1.02599"}]

**Comment by yaskael** [comment]
work done and fixed.
